steps:
  # Step 1: Build and push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform",
        "linux/amd64",
        "-t",
        "gcr.io/cloud-429207/container_2:latest",
        "--push",
        ".",
      ]

  # Step 2: Set up Kubernetes CLI (kubectl)
  - name: "gcr.io/cloud-builders/kubectl"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Get the GKE cluster credentials
        gcloud container clusters get-credentials gke-cluster --zone us-central1 --project cloud-429207

  # Step 3: Update the deployment in GKE
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/container-2-deployment",
        "container-2=gcr.io/cloud-429207/container_2:latest",
      ]

images:
  - "gcr.io/cloud-429207/container_2:latest"

options:
  logging: CLOUD_LOGGING_ONLY
