steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform",
        "linux/amd64",
        "-t",
        "gcr.io/cloud-428420/container_2:latest",
        "--push",
        ".",
      ]

images:
  - "gcr.io/cloud-428420/container_2:latest"

options:
  logging: CLOUD_LOGGING_ONLY
