version: "3.9"
services:
  container_2:
    platform: linux/amd64
    image: gcr.io/cloud-428420/container_2:latest
    container_name: container_2
    ports:
      - "6001:6001"
    networks:
      - app-network
    volumes:
      - .:/data

networks:
  app-network:
    external: true
